### ISSUE TITLE
Module '"../../node_modules/@robotlegsjs/core/lib"' has no exported member 'Mediator'.ts(

### ISSUE THREAD

**Issue by Laioyu** [RobotlegsJS/RobotlegsJS#151]

**Comment by tiagoschenkel** [comment]
Indeed, the info in the `quickstart` section of the `README` file was outdated, just removed it.

The main concept of the `RobotlegsJS` **core** is to abstract away the view part since this is coupled to the framework that is used.

This is why we provide separate plugins, and on each plugin, there is the implementation of the `IMediator`:

https://github.com/RobotlegsJS/RobotlegsJS-Framework/blob/master/packages/pixi/src/robotlegs/bender/extensions/mediatorMap/api/IMediator.ts
https://github.com/RobotlegsJS/RobotlegsJS-Framework/blob/master/packages/phaser/src/robotlegs/bender/extensions/mediatorMap/api/IMediator.ts
https://github.com/RobotlegsJS/RobotlegsJS-Framework/blob/master/packages/phaser-ce/src/robotlegs/bender/extensions/stateManager/api/IStateHandler.ts
https://github.com/RobotlegsJS/RobotlegsJS-Framework/blob/master/packages/createjs/src/robotlegs/bender/extensions/mediatorMap/api/IMediator.ts
https://github.com/RobotlegsJS/RobotlegsJS-Framework/blob/master/packages/openfl/src/robotlegs/bender/extensions/mediatorMap/api/IMediator.ts

So you first need to decide which framework is used for the view, then install the proper `@robotlegsjs` extension and import the `IMediator` from this plugin.

You can check on each repo the `example` project with the minimal setup.

Sorry for my late answer...

**Comment by tiagoschenkel** [comment]
This project is being archived and development is migrating to https://github.com/RobotlegsJS/RobotlegsJS-Framework/blob/master/packages/core.
